### ISSUE TITLE
Use Laravel's publishes method for SteamAuth's config

### ISSUE THREAD

**Issue by braseidon** [sgtaziz/steamauth#1]
Hi! Instead of manually copying the <code>config/steamauth.php</code> file, it would be best to use Laravel's <code>$this->publishes()</code> method. I can submit the pull request for you if you'd like, I just don't know if this is still being maintained.

**Comment by braseidon** [comment]
Not active ? I made a handful of updates to a fork for those prefer coding standards: https://github.com/braseidon/steamauth

**Comment by sgtaziz** [comment]
Sorry! Been super busy with school lately. Haven't seen the notification of your issue until now. Do you mind making a PR of your current branch?
